-- ============================================================
-- FusionX Smart City - Supabase Database Schema
-- Run this in the Supabase SQL Editor
-- ============================================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis;

-- ============================================================
-- 1. TABLES
-- ============================================================

-- User profiles (linked to Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT CHECK (role IN ('admin', 'operator', 'viewer')) DEFAULT 'viewer',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- IoT sensor telemetry
CREATE TABLE sensor_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id TEXT NOT NULL,
  sensor_type TEXT NOT NULL CHECK (sensor_type IN ('flood', 'pressure', 'gas', 'flow')),
  value FLOAT8 NOT NULL,
  unit TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  location_id TEXT
);

-- Asset registry for city infrastructure
CREATE TABLE pipe_inventory (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  pipe_id TEXT UNIQUE NOT NULL,
  material TEXT CHECK (material IN ('PVC', 'PE', 'Ductile Iron')),
  install_date DATE,
  last_inspection DATE,
  environmental_stress_score FLOAT8 DEFAULT 0.5,
  location_coords GEOMETRY(Point, 4326)
);

-- Citizen complaint management
CREATE TABLE complaints (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users,
  category TEXT,
  description TEXT,
  priority TEXT CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')) DEFAULT 'Low',
  status TEXT DEFAULT 'Open' CHECK (status IN ('Open', 'In Progress', 'Resolved', 'Closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- File upload registry
CREATE TABLE uploaded_files (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users,
  filename TEXT NOT NULL,
  file_type TEXT,
  storage_path TEXT NOT NULL,
  analysis_result JSONB,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- 2. ROW LEVEL SECURITY (RLS)
-- ============================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sensor_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipe_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE uploaded_files ENABLE ROW LEVEL SECURITY;

-- Profiles: users can read/update their own profile
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Sensor data: public read, system-level insert
CREATE POLICY "Public Read Access" ON sensor_data FOR SELECT USING (true);

-- Complaints: authenticated insert, own read
CREATE POLICY "Auth User Insert" ON complaints FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own complaints" ON complaints FOR SELECT USING (auth.uid() = user_id);

-- Pipe inventory: admin-only full access
CREATE POLICY "Admin Full Access" ON pipe_inventory FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Uploaded files: owner access
CREATE POLICY "Users can view own files" ON uploaded_files FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own files" ON uploaded_files FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- 3. TRIGGER: Auto-create profile on signup
-- ============================================================
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', 'viewer');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE handle_new_user();

-- ============================================================
-- 4. SEED: Sample sensor data
-- ============================================================
INSERT INTO sensor_data (sensor_id, sensor_type, value, unit, location_id) VALUES
  ('FLOOD-001', 'flood', 2.45, 'meters', 'K100-EAST'),
  ('FLOOD-002', 'flood', 1.90, 'meters', 'K100-WEST'),
  ('PRESS-001', 'pressure', 98.7, 'PSI', 'ZONE-A'),
  ('PRESS-002', 'pressure', 102.3, 'PSI', 'ZONE-B'),
  ('GAS-001', 'gas', 0.02, 'ppm', 'SECTOR-7'),
  ('FLOW-001', 'flow', 450.5, 'L/min', 'MAIN-DIST');

-- ============================================================
-- 5. REALTIME
-- ============================================================
ALTER PUBLICATION supabase_realtime ADD TABLE sensor_data;
ALTER PUBLICATION supabase_realtime ADD TABLE complaints;
